### ISSUE TITLE
Manual install not working

### ISSUE THREAD

**Issue by NeedToMeet** [daylightstudio/FUEL-CMS-Sync-Module#1]
I have followed the directions to manually install and the module is not appearing in the admin. I confirmed that PHP cli is working and ran from the fuel installation directory.

**Comment by daylightstudio** [comment]
Did you place the contents of the downloaded zip file in a folder called "sync" at fuel/modules/sync? By contents, I mean you would have a fuel/modules/sync/assets/...,  fuel/modules/sync/assets/config...,  fuel/modules/sync/assets/controllers/..., etc.

Also, in the fuel/application/config/MY_fuel.php file, is there a 'sync' value under the $config['modules_allowed'](the installer should automatically add that).

**Comment by NeedToMeet** [comment]
Thanks for your fast reply, I hadn't added it to the allowed modules, looks like it's working now, thanks!
